apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-consumer
      color: green
    template:
      metadata:
        labels:
          app: pod-consumer
          color: green
        sped:
          containers:
            - name: pod-consumer
              image: localhost:5000/localconsumer:0.0.2
              ports:
                - containerPort: 8224