#spring.application.name=localkfkconsumer
server:
  port: 8224
  servlet:
    context-path: /sub

spring:
  kafka:
    bootstrap-server: localhost:9092

local:
  brokers: localhost:9092

topic:
  promotion: local.promotion

group:
  promotion: local.promotion
